### ISSUE TITLE
Failure to Model

### ISSUE THREAD

**Issue by sempervictus** [daviswr/ZenPacks.daviswr.Aruba.Instant#3]
These devices were previously modeled successfully, been monitored all day on a test deployment. I added some basic modeler plugins for interfaces and all the normal snmp basics and started getting this:
```
2021-09-18 04:33:13,641 ERROR zen.ZenModeler: Problem while executing plugin daviswr.snmp.ArubaInstant
2021-09-18 04:33:13,641 ERROR zen.ZenModeler: Traceback (most recent call last):
File "/opt/zenoss/Products/DataCollector/zenmodeler.py", line 669, in processClient
datamaps = plugin.process(device, results, self.log)
File "/var/zenoss/ZenPackSource/ZenPacks.daviswr.Aruba.Instant/ZenPacks/daviswr/Aruba/Instant/modeler/plugins/daviswr/snmp/ArubaInstant.py", line 357, in process
del getdata['title']
KeyError: 'title'
```

**Comment by daviswr** [comment]
It should check for presence of the key 'title' in the getdata dict before trying to remove it now, 2b00ece91b3245c4b12219613e9597fdeb255a9c .

The pack sets these modeler plugins on /Network/Aruba/Instant by default:
- zenoss.snmp.DeviceMap
- zenoss.snmp.InterfaceMap
- zenoss.snmp.SnmpV3EngineIdMap
- daviswr.snmp.ArubaInstant

Curious what else you're modeling on the IAP? SNMP on these doesn't appear expose much more than IF-MIB and AI-AP-MIB.

Been building this pack with some AP-224s running 8.6.0, what are you using?

Also, I had to do a double-take on the repo name when I saw the notification email ;)

**Comment by sempervictus** [comment]
Oh yeah, i love your zenpacks - probably the most professional "still maintained" ones around.
Plugins are minimal:
![image](https://user-images.githubusercontent.com/1331084/133907288-231d8ec3-ed34-4248-8ce6-6418f446ca43.png)
Interestingly enough, after restarting Zenoss it seems to work again.

We're transitioning from 4.x to 6.x right now so this might all be Zenoss' own weirdness in the modern construct (like i've noticed that the network map wont update elements until Zenoss is restarted)

**Comment by sempervictus** [comment]
Weirder things afoot, it seems.
Now i'm getting s slew of bad XML errors :-\
```
2021-09-28 14:01:53,052 ERROR zen.zencommand: Error Running Parser <Products.DataCollector.Plugins.PluginLoader instance at 0x12c02bd8>
Traceback (most recent call last):
  File "/opt/zenoss/Products/ZenRRD/zencommand.py", line 588, in _processDatasourceResults
    parser.processResults(datasource, results)
  File "/var/zenoss/ZenPackSource/ZenPacks.daviswr.Aruba.Instant/ZenPacks/daviswr/Aruba/Instant/parsers/nmap.py", line 47, in processResults
    parse_tree = etree.fromstring(cmd.result.output)
  File "src/lxml/lxml.etree.pyx", line 3213, in lxml.etree.fromstring (src/lxml/lxml.etree.c:77697)
  File "src/lxml/parser.pxi", line 1819, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:116494)
  File "src/lxml/parser.pxi", line 1707, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:115144)
  File "src/lxml/parser.pxi", line 1079, in lxml.etree._BaseParser._parseDoc (src/lxml/lxml.etree.c:109543)
  File "src/lxml/parser.pxi", line 573, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:103404)
  File "src/lxml/parser.pxi", line 683, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:105058)
  File "src/lxml/parser.pxi", line 624, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:104201)
XMLSyntaxError: None,
Error Running Parser <Products.DataCollector.Plugins.PluginLoader instance at 0x12c02bd8>
Traceback (most recent call last):
  File "/opt/zenoss/Products/ZenRRD/zencommand.py", line 588, in _processDatasourceResults
    parser.processResults(datasource, results)
  File "/var/zenoss/ZenPackSource/ZenPacks.daviswr.Aruba.Instant/ZenPacks/daviswr/Aruba/Instant/parsers/nmap.py", line 47, in processResults
    parse_tree = etree.fromstring(cmd.result.output)
  File "src/lxml/lxml.etree.pyx", line 3213, in lxml.etree.fromstring (src/lxml/lxml.etree.c:77697)
  File "src/lxml/parser.pxi", line 1819, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:116494)
  File "src/lxml/parser.pxi", line 1707, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:115144)
  File "src/lxml/parser.pxi", line 1079, in lxml.etree._BaseParser._parseDoc (src/lxml/lxml.etree.c:109543)
  File "src/lxml/parser.pxi", line 573, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:103404)
  File "src/lxml/parser.pxi", line 683, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:105058)
  File "src/lxml/parser.pxi", line 624, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:104201)
XMLSyntaxError: None
```

**Comment by daviswr** [comment]
Is this on 6.x or 4.2.5? I haven't been able to keep a single-host 6 stable in my home environment and thus still develop on 4.2.5... so it's completely untested on the newer architecture.

Would be nice to see snippets of a zencommand debug log with `--showrawresults` and `--showfullcommand`, to see if the call to `$ZENHOME/bin/nmap` even works and what its output is.

**Comment by daviswr** [comment]
I'll see about adding some error handling in the mean time.

**Comment by daviswr** [comment]
Try 11303c37005ed7ca9eefe19eeaf25d05c5cfcadc ?

**Comment by sempervictus** [comment]
Confirm it works at current revision for all our targets, thank you!
